/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.konek;

/**
 *
 * @author User
 */
public class data extends javax.swing.JFrame {

    /**
     * Creates new form data
     */
    public data() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void kosong() {
    txtNim.setText("");
    txtNama.setText("");
    cbJKelamin.setSelectedItem("Laki-laki");
    cbJurusan.setSelectedItem("Sistem Indormasi");
    txtTtl.setText("");
    txtAlamat.setText("");
    txtId.setText("");
    }
    
    private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No");
        tbl.addColumn("NIM");
        tbl.addColumn("Nama");
        tbl.addColumn("Jenis Kelamin");
        tbl.addColumn("Jurusan");
        tbl.addColumn("Tempat Tanggal Lahir");
        tbl.addColumn("Alamat");
        table.setModel(tbl);
        
        try{
            Statement statement = (Statement) konek.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from mahasiswa");
            int no = 1;
            while(res.next()) {
                tbl.addRow(new Object []{
                    no++,
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("gender"),
                    res.getString("jurusan"),
                    res.getString("ttl"),
                    res.getString("alamat"),
                });
                table.setModel(tbl);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cbJKelamin = new javax.swing.JComboBox<>();
        cbJurusan = new javax.swing.JComboBox<>();
        txtTtl = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NIM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        jLabel2.setText("Nama Mahasiswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jLabel3.setText("Jurusan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jLabel5.setText("Tempat Tanggal Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, -1, -1));

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("Aplikasi Data Mahasiswa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });
        getContentPane().add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 61, 147, -1));
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 87, 147, -1));

        cbJKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cbJKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJKelaminActionPerformed(evt);
            }
        });
        getContentPane().add(cbJKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 113, 147, -1));

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem Informasi", "Manajemen Informasi", "Teknik Informatika" }));
        cbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJurusanActionPerformed(evt);
            }
        });
        getContentPane().add(cbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 139, 147, -1));

        txtTtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTtlActionPerformed(evt);
            }
        });
        getContentPane().add(txtTtl, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 165, 147, -1));

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 191, 147, -1));

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 222, -1, -1));

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        getContentPane().add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 222, -1, -1));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 222, -1, -1));

        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 64, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 61, 153, -1));

        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });
        getContentPane().add(bCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 95, -1, -1));

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 222, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, -1, 89));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void cbJKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJKelaminActionPerformed

    private void txtTtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTtlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTtlActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void cbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJurusanActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
        
            
    }//GEN-LAST:event_bTambahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String nim = txtNim.getText();
        String nama = txtNama.getText();
        String gender = (String) cbJKelamin.getSelectedItem();
        String jurusan = (String) cbJurusan.getSelectedItem();
        String ttl = txtTtl.getText();
        String alamat = txtAlamat.getText();
        String id = txtId.getText();
        
        try {
            Statement statement = (Statement) konek.getConnection().createStatement();
            int sql = 0;
            statement.executeUpdate("INSERT INTO mahasiswa VALUES ('"+ sql +"','" + nim +"', '"+ nama +"','"+ gender +"','"+ jurusan +"', '"+ ttl +"', '"+ alamat +"')");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
          
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        kosong();
        datatable();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
         try{
            Statement statement = (Statement) konek.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from mahasiswa WHERE id ='"+ txtId.getText() +"'");
            while(res.next()) {
                txtNim.setText(res.getString("nim"));
                txtNama.setText(res.getString("nama"));
                cbJKelamin.setSelectedItem(res.getString("gender"));
                cbJurusan.setSelectedItem(res.getString("jurusan"));
                txtTtl.setText(res.getString("ttl"));
                txtAlamat.setText(res.getString("alamat"));
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }//GEN-LAST:event_bCariActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE mahasiswa SET nim ='" + txtNim.getText() +"', nama='"+ txtNama.getText()+"', gender='"+ cbJKelamin.getSelectedItem() +"', jurusan='"+ cbJurusan.getSelectedItem() +"', ttl='"+ txtTtl.getText() +"', alamat='"+ txtAlamat.getText() +"' WHERE nim = '"+ txtNim.getText() +"' ";
            Statement statement = (Statement) konek.getConnection().createStatement();
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            
        } catch(SQLException e)  {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        kosong();
        datatable();
    }//GEN-LAST:event_bUbahActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris = table.rowAtPoint(evt.getPoint());
        String nim = table.getValueAt(baris, 1).toString();
        txtNim.setText(nim);
        String nama = table.getValueAt(baris,2).toString();
        txtNama.setText(nama);
        String gender = table.getValueAt(baris,3).toString();
        cbJKelamin.setSelectedItem(gender);
        String jurusan = table.getValueAt(baris, 4).toString();
        cbJurusan.setSelectedItem(jurusan);
        String ttl = table.getValueAt(baris,5).toString();
        txtTtl.setText(ttl);
        String alamat = table.getValueAt(baris, 6).toString();
        txtAlamat.setText(alamat);
        
    }//GEN-LAST:event_tableMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM mahasiswa WHERE nim ='" + txtNim.getText() +"'";
            Statement statement = (Statement) konek.getConnection().createStatement();
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            
        } catch(SQLException e)  {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        kosong();
        datatable();
    }//GEN-LAST:event_bHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbJKelamin;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTtl;
    // End of variables declaration//GEN-END:variables
}
